version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PASS: password
    ports:
      - "3000:3000"
    depends_on:
      - postgres
