name: Docker Build and Upload to JFrog Artifactory

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64 -t  nodejs:v1 --push .
        
    - name: Tag Docker image for JFrog Artifactory
      run: |
        docker tag nodejs:v1 devopscloud592.jfrog.io/docker/nodejs:v1    

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        jfrog-cli-version: latest

    - name: Configure JFrog CLI
      run: |
        jfrog config add devops-artifactory \
          --artifactory-url https://devopscloud592.jfrog.io/artifactory \
          --user ${{ secrets.JFROG_USERNAME }} \
          --password ${{ secrets.JFROG_PASSWORD }}

    - name: Upload Docker image to JFrog Artifactory
      env:
        JFROG_CLI_HOME: /home/runner/jfrog
        JFROG_CLI_OFFER_CONFIG: false
      run: |
        jfrog rt docker-push devopscloud592.jfrog.io/docker/nodejs:v1 docker-local-repo
